services:
  custom:
    env_file:
    - .env
    image: wonli/app:${TAG}
    container_name: "wonli-app"
    restart: always
    ports:
      - "8081:80" # <Port exposed> : <MySQL Port running inside container>
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
