version: "3.3"
services:
  db:
    image: mysql:8.3.0
    container_name: "mysql"
    restart: always
    command: --default-authentification-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "db"
      #MYSQL_USER: 'user'     # So you don't have to use root, but you can if you like
      #MYSQL_PASSWORD: 'password'     # You can use whatever password you like
      MYSQL_ROOT_PASSWORD: { MYSQL_ROOT_PASSWORD } # Password for root access
    ports:
      - "3306:3306" # <Port exposed> : <MySQL Port running inside container>
    expose:
      - "3306" # Opens port 3306 on the container
    volumes:
      - ./data/my-data:/var/lib/mysql # Where our data will be persisted
# Names our volume

#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin
#    container_name: 'phpmyadmin'
#    restart: always
#    ports:
#      - "8090:80"
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: 'root'

# h2:
#   container_name: MyH2Instance
#   image: oscarfonts/h2
#   restart: always
#   ports:
#     - 1521:1521
#     - 81:81
#   environment:
#     - H2_OPTIONS=-ifNotExists
#   volumes:
#     - ./data/h2_data:/opt/h2-data

volumes:
  my-db:
