version: "3.3"
services:
  custom:
    image: wonli/app
    container_name: "wonli-app"
    restart: always
    ports:
      - "8090:80" # <Port exposed> : <MySQL Port running inside container>
    networks:
      - app-network

networks:
  app-network:
    external: true
